export const dummyStudent = {
  regNumber: '2020/123456',
  email: 'student@unn.edu.ng',
  phone: '+2348150740406',
  firstName: 'Chimdi',
  lastName: 'Ezechukwu',
  username: '0x0000',
  department: 'Computer Science',
  walletBalance: 5000,
  nfcCardId: 'NFC-2024-001',
  profilePhoto: null,
};

export const dummyTransactions = [
  {
    id: 'SHU91873D5E51E1',
    date: '18th November, 2025',
    route: 'Ikpa Road - UNN Main Gate',
    busNumber: 'UNN-BUS-12',
    amount: 200,
    type: 'tap',
    status: 'success',
    time: '08:45 AM',
    paymentMethod: 'card',
    from: 'Ikpa Road Junction',
    to: 'UNN Main Gate',
  },
  {
    id: 'SHU13B0215C9C96E',
    date: '18th November, 2025',
    route: 'Odim - Carpark',
    busNumber: 'UNN-BUS-05',
    amount: 150,
    type: 'tap',
    status: 'success',
    time: '02:30 PM',
    paymentMethod: 'phone',
    from: 'Odim Junction',
    to: 'University Carpark',
  },
  {
    id: 'SHU57B67B044A337',
    date: '17th November, 2025',
    route: 'UNN Main Gate - Enugu',
    busNumber: 'UNN-BUS-08',
    amount: 500,
    type: 'tap',
    status: 'success',
    time: '06:15 PM',
    paymentMethod: 'qrcode',
    from: 'UNN Main Gate',
    to: 'Enugu (Ogui Road)',
  },
  {
    id: 'SHU7D44085D757C3',
    date: '17th November, 2025',
    route: 'Carpark - Nsukka Town',
    busNumber: 'UNN-BUS-03',
    amount: 200,
    type: 'tap',
    status: 'success',
    time: '11:20 AM',
    paymentMethod: 'card',
    from: 'University Carpark',
    to: 'Nsukka Market Square',
  },
  {
    id: 'SHU182C8D6A25B3A3',
    date: '16th November, 2025',
    route: 'Stadium - Zik Flats',
    busNumber: 'UNN-BUS-07',
    amount: 100,
    type: 'tap',
    status: 'success',
    time: '04:10 PM',
    paymentMethod: 'transfer',
    from: 'UNN Stadium',
    to: 'Zik Flats (Aluta)',
  },
  {
    id: 'SHU105BF77071999',
    date: '16th November, 2025',
    route: 'UNN Main Gate - Faculty Area',
    busNumber: 'UNN-BUS-12',
    amount: 100,
    type: 'tap',
    status: 'success',
    time: '09:30 AM',
    paymentMethod: 'phone',
    from: 'UNN Main Gate',
    to: 'Faculty of Arts',
  },
  {
    id: 'SHU2CD216D89600C',
    date: '15th November, 2025',
    route: 'Nsukka Town - 9th Mile',
    busNumber: 'UNN-BUS-04',
    amount: 400,
    type: 'tap',
    status: 'success',
    time: '07:00 AM',
    paymentMethod: 'qrcode',
    from: 'Nsukka Market Square',
    to: '9th Mile Corner',
  },
  {
    id: 'SHU3F15D2B4A7C2E',
    date: '15th November, 2025',
    route: 'Faculty - Main Gate',
    busNumber: 'UNN-BUS-06',
    amount: 100,
    type: 'tap',
    status: 'success',
    time: '01:45 PM',
    paymentMethod: 'card',
    from: 'Faculty of Engineering',
    to: 'UNN Main Gate',
  },
  {
    id: 'SHU4E26A8F5B9D1C',
    date: '14th November, 2025',
    route: 'Ikpa Road - Faculty Area',
    busNumber: 'UNN-BUS-12',
    amount: 150,
    type: 'tap',
    status: 'success',
    time: '10:15 AM',
    paymentMethod: 'phone',
    from: 'Ikpa Road Junction',
    to: 'Faculty of Arts',
  },
  {
    id: 'SHU5G37B9G6C0E2D',
    date: '14th November, 2025',
    route: 'Carpark - Stadium',
    busNumber: 'UNN-BUS-02',
    amount: 100,
    type: 'tap',
    status: 'success',
    time: '05:30 PM',
    paymentMethod: 'qrcode',
    from: 'University Carpark',
    to: 'UNN Stadium',
  },
  {
    id: 'SHU6H48C0H7D1F3E',
    date: '13th November, 2025',
    route: 'Zik Flats - UNN Main Gate',
    busNumber: 'UNN-BUS-11',
    amount: 200,
    type: 'tap',
    status: 'success',
    time: '08:00 AM',
    paymentMethod: 'transfer',
    from: 'Zik Flats (Aluta)',
    to: 'UNN Main Gate',
  },
  {
    id: 'SHU7I59D1I8E2G4F',
    date: '13th November, 2025',
    route: 'Odim - Faculty',
    busNumber: 'UNN-BUS-09',
    amount: 150,
    type: 'tap',
    status: 'success',
    time: '12:30 PM',
    paymentMethod: 'card',
    from: 'Odim Junction',
    to: 'Faculty of Sciences',
  },
  {
    id: 'SHU8J60E2J9F3H5G',
    date: '12th November, 2025',
    route: 'UNN Main Gate - Carpark',
    busNumber: 'UNN-BUS-03',
    amount: 100,
    type: 'tap',
    status: 'success',
    time: '09:00 AM',
    paymentMethod: 'phone',
    from: 'UNN Main Gate',
    to: 'University Carpark',
  },
  {
    id: 'SHU9K71F3K0G4I6H',
    date: '12th November, 2025',
    route: 'Nsukka Town - Stadium',
    busNumber: 'UNN-BUS-07',
    amount: 250,
    type: 'tap',
    status: 'success',
    time: '03:20 PM',
    paymentMethod: 'qrcode',
    from: 'Nsukka Market Square',
    to: 'UNN Stadium',
  },
  {
    id: 'SHU0L82G4L1H5J7I',
    date: '11th November, 2025',
    route: 'Ikpa Road - Stadium',
    busNumber: 'UNN-BUS-08',
    amount: 200,
    type: 'tap',
    status: 'success',
    time: '07:45 AM',
    paymentMethod: 'transfer',
    from: 'Ikpa Road Junction',
    to: 'UNN Stadium',
  },
  {
    id: 'SHU1M93H5M2I6K8J',
    date: '11th November, 2025',
    route: 'Faculty - Carpark',
    busNumber: 'UNN-BUS-05',
    amount: 100,
    type: 'tap',
    status: 'success',
    time: '02:00 PM',
    paymentMethod: 'card',
    from: 'Faculty of Medicine',
    to: 'University Carpark',
  },
  {
    id: 'SHU2N04I6N3J7L9K',
    date: '10th November, 2025',
    route: 'UNN Main Gate - Enugu',
    busNumber: 'UNN-BUS-01',
    amount: 500,
    type: 'tap',
    status: 'success',
    time: '06:30 AM',
    paymentMethod: 'phone',
    from: 'UNN Main Gate',
    to: 'Enugu (Ogui Road)',
  },
  {
    id: 'SHU3O15J7O4K8M0L',
    date: '10th November, 2025',
    route: 'Odim - Zik Flats',
    busNumber: 'UNN-BUS-04',
    amount: 150,
    type: 'tap',
    status: 'success',
    time: '04:15 PM',
    paymentMethod: 'qrcode',
    from: 'Odim Junction',
    to: 'Zik Flats (Aluta)',
  },
];

export const dummyDriver = {
  firstName: 'John',
  lastName: 'Okeke',
  email: 'john.driver@unn.edu.ng',
  phone: '+2348012345678',
  busNumber: 'UNN-BUS-12',
  plateNumber: 'NSK-456-XY',
  licenseNumber: 'UNN-DL-2024-012',
  walletBalance: 45000,
  bankDetails: {
    accountNumber: '0123456789',
    bankName: 'First Bank of Nigeria',
    accountName: 'John Okeke',
  },
  weeklyStats: {
    totalPassengers: 156,
    totalEarnings: 31200,
    tripsMade: 42,
  },
  route: 'Ikpa Road - UNN Main Gate',
};

export const dummyDriverTrips = [
  {
    id: 'TRP001',
    date: '17th November, 2025',
    time: '08:45 AM',
    studentName: 'Chimdi Ezechukwu',
    studentId: '2020/123456',
    cardId: 'NFC-2024-001',
    route: 'Ikpa Road - UNN Main Gate',
    fare: 200,
    status: 'completed',
    paymentMethod: 'card',
    from: 'Ikpa Road Junction',
    to: 'UNN Main Gate',
  },
  {
    id: 'TRP002',
    date: '17th November, 2025',
    time: '09:15 AM',
    studentName: 'Ada Okafor',
    studentId: '2021/234567',
    cardId: 'NFC-2024-015',
    route: 'Ikpa Road - UNN Main Gate',
    fare: 200,
    status: 'completed',
    paymentMethod: 'phone',
    from: 'Ikpa Road Junction',
    to: 'UNN Main Gate',
  },
  {
    id: 'TRP003',
    date: '17th November, 2025',
    time: '10:30 AM',
    studentName: 'Chidi Nnaji',
    studentId: '2022/345678',
    cardId: 'NFC-2024-028',
    route: 'Ikpa Road - Faculty Area',
    fare: 150,
    status: 'completed',
    paymentMethod: 'qrcode',
    from: 'Ikpa Road Junction',
    to: 'Faculty of Arts',
  },
  {
    id: 'TRP004',
    date: '17th November, 2025',
    time: '11:45 AM',
    studentName: 'Ngozi Obi',
    studentId: '2020/456789',
    cardId: 'NFC-2024-042',
    route: 'UNN Main Gate - Carpark',
    fare: 100,
    status: 'completed',
    paymentMethod: 'transfer',
    from: 'UNN Main Gate',
    to: 'University Carpark',
  },
  {
    id: 'TRP005',
    date: '17th November, 2025',
    time: '02:15 PM',
    studentName: 'Emeka Uche',
    studentId: '2021/567890',
    cardId: 'NFC-2024-056',
    route: 'Zik Flats - Stadium',
    fare: 100,
    status: 'completed',
    paymentMethod: 'card',
    from: 'Zik Flats (Aluta)',
    to: 'UNN Stadium',
  },
  {
    id: 'TRP006',
    date: '16th November, 2025',
    time: '08:30 AM',
    studentName: 'Blessing Okoro',
    studentId: '2022/678901',
    cardId: 'NFC-2024-063',
    route: 'Nsukka Town - UNN',
    fare: 200,
    status: 'completed',
    paymentMethod: 'phone',
    from: 'Nsukka Market Square',
    to: 'UNN Main Gate',
  },
  {
    id: 'TRP007',
    date: '16th November, 2025',
    time: '10:00 AM',
    studentName: 'Chioma Eze',
    studentId: '2020/789012',
    cardId: 'NFC-2024-071',
    route: 'Carpark - Odim',
    fare: 150,
    status: 'completed',
    paymentMethod: 'qrcode',
    from: 'University Carpark',
    to: 'Odim Junction',
  },
  {
    id: 'TRP008',
    date: '16th November, 2025',
    time: '01:20 PM',
    studentName: 'Ifeanyi Chukwu',
    studentId: '2021/890123',
    cardId: 'NFC-2024-085',
    route: 'Faculty Area - Main Gate',
    fare: 100,
    status: 'completed',
    paymentMethod: 'card',
    from: 'Faculty of Engineering',
    to: 'UNN Main Gate',
  },
];

export const dummyStats = {
  totalTrips: 56,
  totalSpent: 11850,
  activeCard: 'NFC-2024-001',
  lastRide: '18th Nov, 2025',
};

export const dummyCardRequests = [
  {
    id: '1',
    studentName: 'Chimdi Ezechukwu',
    regNumber: '2020/123456',
    email: 'student@unn.edu.ng',
    status: 'pending',
    requestedAt: '2025-11-15T10:30:00Z',
  },
  {
    id: '2',
    studentName: 'Ada Okafor',
    regNumber: '2021/234567',
    email: 'ada.okafor@unn.edu.ng',
    status: 'pending',
    requestedAt: '2025-11-14T14:20:00Z',
  },
];

export const dummyRefundRequests = [
  {
    id: '1',
    studentName: 'Chimdi Ezechukwu',
    regNumber: '2020/123456',
    transactionId: 'SHU91873D5E51E1',
    amount: 200,
    reason: 'Bus did not complete the route',
    status: 'pending',
    requestedAt: '2025-11-16T09:15:00Z',
  },
];

export const shuttleRoutes = [
  {
    id: '1',
    name: 'Ikpa - Main Gate',
    from: 'Ikpa Road Junction',
    to: 'UNN Main Gate',
    fare: 200,
    duration: '15 mins',
  },
  {
    id: '2',
    name: 'Carpark - Faculty',
    from: 'University Carpark',
    to: 'Faculty Area',
    fare: 100,
    duration: '10 mins',
  },
  {
    id: '3',
    name: 'Enugu Express',
    from: 'UNN Main Gate',
    to: 'Enugu (Ogui Road)',
    fare: 500,
    duration: '45 mins',
  },
  {
    id: '4',
    name: 'Campus Loop',
    from: 'UNN Stadium',
    to: 'Zik Flats (Aluta)',
    fare: 100,
    duration: '8 mins',
  },
  {
    id: '5',
    name: 'Nsukka Town',
    from: 'Nsukka Market Square',
    to: 'UNN Main Gate',
    fare: 200,
    duration: '12 mins',
  },
];
